config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :docker_cfgs
  resources :docker_images
  root 'home#index'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

class User < ActiveRecord::Base
  has_one :docker_cfg
  validates :name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :email, email: true

  def dockerconf
    return {} if docker_cfg_id.nil?
    dc = DockerCfg.find(docker_cfg_id)
    return {} if dc.nil?
    dockerconf= {
   	 dc.url =>
	   {
	     "auth" => dc.auth,
	     "email" => dc.email
	   }
    }
  end

  def self.from_omniauth(auth)
    return nil if auth.nil?
    return nil unless auth["provider"] && auth["uid"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["nickname"]
      user.email = auth["info"]["email"]
      dc = DockerCfg.new
      dc.url = "set the docker config url"
      dc.auth = "set the docker config auth"
      dc.email = user.email
      dc.save
      user.docker_cfg_id = dc.id
    end 
  end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if !params[:docker_cfg_id]
      dc = DockerCfg.new
      dc.url = "set the docker config url"
      dc.auth = "set the docker config auth"
      dc.email = @user.email
      dc.save
      @user.docker_cfg_id = dc.id
    end

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :docker_cfg_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <% if is_admin? %>
    <div class="field">
      <%= f.label :docker_cfg_id %><br>
      <%= f.number_field :docker_cfg_id %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<% if is_admin? %>
<%= link_to 'Back', users_path %>
<% end %>
<%= link_to 'Back to home', "/" %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Docker cfg</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <% if user.docker_cfg_id %>
          <td><%= link_to user.docker_cfg_id, DockerCfg.find_by_id(user.docker_cfg_id) %></td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<p><%= link_to 'Back', "/" %></p>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Docker cfg:</strong>
  <% if DockerCfg.find_by_id(@user.docker_cfg_id).nil? %>
    Error: there is no docker configuration
  <% else %>
    <%= link_to @user.docker_cfg_id, docker_cfg_path(DockerCfg.find_by_id(@user.docker_cfg_id)) %>
  <% end %>

</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<% if is_admin? %>
<%= link_to 'Back', users_path %>
<% end %>
<%= link_to 'Back to home', "/" %>