config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :docker_cfgs
  resources :docker_images
  root 'home#index'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if current_user %>
  <% dc = DockerCfg.find_by_id(current_user.docker_cfg_id) %>
  <% if dc.nil? || dc.url == "set the docker config url" || dc.auth == "set the docker config auth" %>
    <p><%= link_to "Please set the docker configuration", docker_cfg_path(dc) %></p>
  <% end %>
<% end %>
<% if current_user %>
<h2><%= current_user.name %>'s images</h2>
<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Repository name</th>
      <% if is_admin? %>
        <th>user</th>
      <% end %>
      <th>Last check</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% DockerImage.all.each do |docker_image| %>
      <tr>
        <% next if docker_image.user_id.to_s != current_user.id.to_s %>
        <td><%= docker_image.user_name %></td>
        <td><%= docker_image.repository_name %></td>
        <td>
          <% if docker_image.runs && docker_image.runs.length > 0 %>
            <%= docker_image.runs.last.stop %> 
          <% else %>
            Not checked yet
          <% end %>
        </td>
        <td>
          <% if docker_image.runs && docker_image.runs.length > 0 %>
            <% if docker_image.runs.last.success %>
              <div style="color: green">Ok</div>
            <% else %>
              <div style="color: red">Failed</div>
            <% end %>
          <% else %>
            Not checked yet
          <% end %>
        </td>
        <td><%= link_to 'Show', docker_image %></td>
        <td><%= link_to 'Edit', edit_docker_image_path(docker_image) %></td>
        <td><%= link_to 'Destroy', docker_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Docker image', new_docker_image_path %>
<% end %>
<h2>All images</h2>
<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Repository name</th>
      <% if is_admin? %>
        <th>user</th>
      <% end %>
      <th>Last check</th>
      <th>Result</th>
      <% if is_admin? %>
        <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% DockerImage.all.each do |docker_image| %>
      <tr>
        <td><%= docker_image.user_name %></td>
        <td><%= docker_image.repository_name %></td>
        <% if is_admin? %>
          <td><%= link_to docker_image.user_id, User.find_by_id(docker_image.user_id) %></td>
        <% end %>
        <td>
          <% if docker_image.runs && docker_image.runs.length > 0 %>
            <%= docker_image.runs.last.stop %> 
          <% else %>
            Not checked yet
          <% end %>
        </td>
        <td>
          <% if docker_image.runs && docker_image.runs.length > 0 %>
            <% if docker_image.runs.last.success %>
              <div style="color: green">Ok</div>
            <% else %>
              <div style="color: red">Failed</div>
            <% end %>
          <% else %>
            Not checked yet
          <% end %>
        </td>
        <% if is_admin? %>
          <td><%= link_to 'Show', docker_image %></td>
          <td><%= link_to 'Edit', edit_docker_image_path(docker_image) %></td>
          <td><%= link_to 'Destroy', docker_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>