config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :docker_cfgs
  resources :docker_images
  root 'home#index'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/docker_cfg.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

class DockerCfg < ActiveRecord::Base
  belongs_to :user
  validates :url, presence: true
  validates :auth, presence: true
  validates :email, presence: true
  validates :email, email: true
end

app/controllers/docker_cfgs_controller.rb
class DockerCfgsController < ApplicationController
  before_action :set_docker_cfg, only: [:show, :edit, :update, :destroy]

  # GET /docker_cfgs
  # GET /docker_cfgs.json
  def index
    @docker_cfgs = DockerCfg.all
  end

  # GET /docker_cfgs/1
  # GET /docker_cfgs/1.json
  def show
  end

  # GET /docker_cfgs/new
  def new
    @docker_cfg = DockerCfg.new
  end

  # GET /docker_cfgs/1/edit
  def edit
  end

  # POST /docker_cfgs
  # POST /docker_cfgs.json
  def create
    @docker_cfg = DockerCfg.new(docker_cfg_params)

    respond_to do |format|
      if @docker_cfg.save
        format.html { redirect_to @docker_cfg, notice: 'Docker cfg was successfully created.' }
        format.json { render :show, status: :created, location: @docker_cfg }
      else
        format.html { render :new }
        format.json { render json: @docker_cfg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docker_cfgs/1
  # PATCH/PUT /docker_cfgs/1.json
  def update
    respond_to do |format|
      if @docker_cfg.update(docker_cfg_params)
        format.html { redirect_to @docker_cfg, notice: 'Docker cfg was successfully updated.' }
        format.json { render :show, status: :ok, location: @docker_cfg }
      else
        format.html { render :edit }
        format.json { render json: @docker_cfg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docker_cfgs/1
  # DELETE /docker_cfgs/1.json
  def destroy
    @docker_cfg.destroy
    respond_to do |format|
      format.html { redirect_to docker_cfgs_url, notice: 'Docker cfg was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_docker_cfg
      @docker_cfg = DockerCfg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def docker_cfg_params
      params.require(:docker_cfg).permit(:url, :auth, :email)
    end
end

app/helpers/docker_cfgs_helper.rb
module DockerCfgsHelper
end

app/views/docker_cfgs/_form.html.erb
<%= form_for(@docker_cfg) do |f| %>
  <% if @docker_cfg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@docker_cfg.errors.count, "error") %> prohibited this docker_cfg from being saved:</h2>

      <ul>
      <% @docker_cfg.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :auth %><br>
    <%= f.text_field :auth %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/docker_cfgs/edit.html.erb
<h1>Editing Docker Cfg</h1>

<%= render 'form' %>

<%= link_to 'Show', @docker_cfg %> |
<% if is_admin? %>
  <%= link_to 'Back', docker_cfgs_path %>
<% end %>

app/views/docker_cfgs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Docker Cfgs</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Auth</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @docker_cfgs.each do |docker_cfg| %>
      <tr>
        <td><%= docker_cfg.url %></td>
        <td><%= docker_cfg.auth %></td>
        <td><%= docker_cfg.email %></td>
        <td><%= link_to 'Show', docker_cfg %></td>
        <td><%= link_to 'Edit', edit_docker_cfg_path(docker_cfg) %></td>
        <td><%= link_to 'Destroy', docker_cfg, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Docker cfg', new_docker_cfg_path %>
<p><%= link_to 'Back', "/" %></p>

app/views/docker_cfgs/new.html.erb
<h1>New Docker Cfg</h1>

<%= render 'form' %>

<%= link_to 'Back', docker_cfgs_path %>

app/views/docker_cfgs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @docker_cfg.url %>
</p>

<p>
  <strong>Auth:</strong>
  <%= @docker_cfg.auth %>
</p>

<p>
  <strong>Email:</strong>
  <%= @docker_cfg.email %>
</p>

<%= link_to 'Edit', edit_docker_cfg_path(@docker_cfg) %> |
<% if is_admin? %>
  <%= link_to 'Back', docker_cfgs_path %>
<% end %>
<%= link_to 'Back to user config', User.find_by_id(current_user.id) %>